[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "TZ=America/New_York npm run build"
  node_bundler = "esbuild"


# Redirect API requests to the Express function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

# Redirect all unknown paths to React's index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

#[build.environment]
#  TZ = "UTC-5:00"

#[[functions.schedule]]
#function = "daily-task"
#cron = "0 0 * * *" 
#schedule = "*/5 * * * *"

[functions."daily-task"]
  schedule = "0 */6 * * *"
