[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"


# Redirect API requests to the Express function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

# Redirect all unknown paths to React's index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
